AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - bin/*
    - db/**/*
    - node_modules/**/*
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
